fix: typos and spelling mistakes.
praveenscience/Internship-LMS-FrontEnd pull request #131
Opened 2021-08-29 09:14 UTC by AyshChaudhary

## Related Issue 

- Info about the related issue 

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

2021-08-29 21:22 UTC, praveenscience requested changes

2021-08-29 21:22 UTC, praveenscience commented on Contributing.md
> +3. Participants/contributors have to **comment** on issues they would like to work on, and mentors or the PA will assign you.
Nopes. Need space.

2021-08-29 21:22 UTC, praveenscience commented on Contributing.md
> +5. Participants/contributors can also **open their issues**, but it needs to be verified and labeled by a mentor. Please discuss with the team once on [**Discord**](https://discord.com/channels/81172
UK / India English - labelled is right. Nopes.

2021-08-29 21:22 UTC, praveenscience commented on Contributing.md
> +**4.** Click on Clone or download button on the forked repository. Make sure you are cloning your version (GitHub.com/\<your username>/Internship-LMS-FrontEnd) and not the CatsInTech organization's.
Use UK / Indian English.

2021-08-29 21:22 UTC, praveenscience commented on Contributing.md
> +Discord is only for GSoC participants.
GSoC ≠ GSSoC

2021-08-30 06:55 UTC, AyshChaudhary commented
Thanks for pointing out my mistakes .

2021-08-30 06:55 UTC, closed without merging