Fix typo in ReadMe.md
praveenscience/Internship-LMS-FrontEnd pull request #14
Opened 2021-01-21 02:38 UTC by TeeVenDick

- Fix typo based on issue #13

2021-01-21 10:46 UTC, praveenscience requested changes

2021-01-21 10:46 UTC, praveenscience commented on ReadMe.md
> +Be awesome and read the following guidelines.
I guess let's get rid of "read the". It was meant to be:
```suggestion
Be awesome and follow the guidelines.
```

2021-01-22 09:24 UTC, praveenscience approved these changes
Looks good to me! 👍

2021-01-25 04:19 UTC, Salonii02 approved these changes

2021-01-25 11:44 UTC, merged