Added config file for Welcome BOT
praveenscience/Internship-LMS-FrontEnd pull request #19
Opened 2021-01-25 11:57 UTC by muthuannamalai12

I have added a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.

2021-01-25 16:33 UTC, praveenscience requested changes
Thanks. Looks almost nice.

2021-01-25 16:33 UTC, praveenscience commented on .github/config.yml
> +  Hello there!👋 Welcome to the project!🚀⚡
Let's have a space before the emojis, please?

2021-01-25 16:33 UTC, praveenscience commented on .github/config.yml
> +
Do we need two line spaces or one? If one, can we just remove the extra line?

2021-01-25 16:33 UTC, praveenscience commented on .github/config.yml
> +
Do we need two line spaces or one? If one, can we just remove the extra line?

2021-01-25 16:33 UTC, praveenscience commented on .github/config.yml
> +
Do we need two line spaces or one? If one, can we just remove the extra line?

2021-01-25 16:33 UTC, praveenscience commented on .github/config.yml
> +  Thank you and congrats🎉 for opening your very first issue in this project. Our project aims to onboard new interns, who have applied to the companies and help them understand the process and make t
Let's have a space before the emojis, please?

2021-01-25 16:33 UTC, praveenscience commented on .github/config.yml
> +  Hello there!👋 Welcome to the project!💖
Let's have a space before the emojis, please?

2021-01-25 16:33 UTC, praveenscience commented on .github/config.yml
> +  Please make sure not to start working on the issue, unless you get assigned to it.😄
Let's have a space before the emojis, please?

2021-01-25 16:33 UTC, praveenscience commented on .github/config.yml
> +  Please adhere to our [Code of Conduct](https://github.com/praveenscience/Internship-LMS-FrontEnd/blob/main/Code_of_Conduct.md).🙌 We will get back to you as soon as we can 😄.
Let's have a space before the emojis, please?

2021-01-25 16:33 UTC, praveenscience commented on .github/config.yml
> +
Do we need two line spaces or one? If one, can we just remove the extra line?

2021-01-26 07:40 UTC, praveenscience approved these changes
LGTM! 👍

2021-01-26 08:49 UTC, Salonii02 approved these changes

2021-01-26 09:47 UTC, merged