Updated Readme
praveenscience/Internship-LMS-FrontEnd pull request #22
Opened 2021-01-29 08:56 UTC by Jassi10000

Mentioned more clearly about what type of database we will actually be using in  mentioned MERN Stack

2021-01-29 09:33 UTC, praveenscience requested changes

2021-01-29 09:33 UTC, praveenscience commented on ReadMe.md
> +
Make it a single line, please. Give a line space. Thanks for this! 😅 Also, why `[ ]` for "We have ..." Use a normal `()` without any spaces inside.

2021-01-29 10:00 UTC, Jassi10000 commented
Done the changes told sir @praveenscience

2021-01-29 13:12 UTC, praveenscience requested changes

2021-01-29 13:12 UTC, praveenscience commented on ReadMe.md
> +    Usually MERN Stack is MongoDB , ExpressJS , ReactJS , NodeJS. But for our product, we need a hierarchical database management system not a document oriented that's why we will be using MySQL or P
Oh, I meant, in the source code view, do the following:

1. Add a line space after the heading.
2. Remove character spaces before each lines.
3. Keep everything what you have written originally in a single line, not multiline.

2021-01-29 14:38 UTC, praveenscience requested changes

2021-01-29 14:38 UTC, praveenscience commented on ReadMe.md
> +<p> Usually MERN Stack is MongoDB , ExpressJS , ReactJS , NodeJS. But for our product, we need a hierarchical database management system not a document oriented that's why we will be using MySQL or P
1. Remove the HTML tags please.
2. Remove the space before the comma.
3. Add the complete text that I sent you.

2021-01-29 18:04 UTC, praveenscience commented on ReadMe.md
> +<p> Usually MERN Stack is MongoDB , ExpressJS , ReactJS , NodeJS. But for our product, we need a hierarchical database management system not a document oriented that's why we will be using MySQL or P
1. Done
2. Not Done.
3. Not Done.

2021-01-29 18:10 UTC, Jassi10000 commented
![image](https://user-images.githubusercontent.com/64856348/106311337-fdeb5780-628a-11eb-8c55-070873239add.png)



Sir pls see my latest commit , I have done all the changes you told @praveenscience 
I have removed the space before comma  and also used the same text you sent to me , and this commit was made by me around an  hour ago , please check this ss for reference

2021-01-29 19:05 UTC, praveenscience commented
@Jassi10000 I'll say you what exactly is done. 😉

2021-01-29 19:08 UTC, praveenscience commented
@Jassi10000 Check the [diff now](https://github.com/praveenscience/Internship-LMS-FrontEnd/pull/22/commits/abb921cdc86daa33e4b9992bc938cb7f507ef44b). If you're using `[]` it becomes a syntax in Markdown. It's crucial to know about these.

2021-01-29 19:08 UTC, praveenscience approved these changes
LGTM! 👍

2021-01-29 19:15 UTC, Jassi10000 commented
> @Jassi10000 Check the [diff now](https://github.com/praveenscience/Internship-LMS-FrontEnd/pull/22/commits/abb921cdc86daa33e4b9992bc938cb7f507ef44b). If you're using `[]` it becomes a syntax in Markdown. It's crucial to know about these.

Yeah sure , thank you for that awesome knowledge 😀

2021-01-29 19:20 UTC, praveenscience commented
@Jassi10000 We'll wait for the other maintainers to give their approval! 😁

2021-01-30 04:11 UTC, Salonii02 approved these changes

2021-01-30 13:08 UTC, merged

2021-01-30 13:37 UTC, manudd1011 reviewed
.