Readme Updated
praveenscience/Internship-LMS-FrontEnd pull request #66
Opened 2021-03-16 14:50 UTC by ayush461

## Related Issue 

Changed the readme format.

Closes: #60
### Describe the changes you've made

I have changed the readme format as per rules.

2021-03-16 15:08 UTC, praveenscience requested changes

2021-03-16 15:08 UTC, praveenscience commented on README.md
> +Front End
Shall we make it bold? What do you suggest?

2021-03-16 15:08 UTC, praveenscience commented on README.md
> +Back End
Shall we make it bold? What do you suggest?

2021-03-16 15:08 UTC, praveenscience commented on README.md
> +Deployment
Shall we make it bold? What do you suggest?

2021-03-16 15:08 UTC, praveenscience commented on README.md
> +### Admin & Mentors
Please add one line space under the first two. 😅

2021-03-16 15:08 UTC, praveenscience commented on README.md
> +</a>
Make it into Markdown.

2021-03-16 15:08 UTC, praveenscience commented on README.md
> +- Make the process smooth.
Where's the automation line? 🤔

2021-03-16 15:17 UTC, ayush461 commented on README.md
> +* Tejan Singh([LinkedIn](https://www.linkedin.com/in/tejansingh/))
@praveenscience sir, spaces should be after every line or only after first line?

2021-03-17 00:09 UTC, praveenscience approved these changes
I'll make it right. 😊

2021-03-17 00:09 UTC, praveenscience commented on README.md
> +* Tejan Singh([LinkedIn](https://www.linkedin.com/in/tejansingh/))
@ayush461 After `Singh` 😅

2021-03-17 00:19 UTC, praveenscience approved these changes
LGTM. I fixed all the issues man! 😊

2021-03-17 00:20 UTC, merged